// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jlvethvtfxqriehnsihu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpsdmV0aHZ0ZnhxcmllaG5zaWh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0MjAxNTcsImV4cCI6MjA2NDk5NjE1N30.LNRKHmmNiYzv2k1Aiu4asyqMJrxalGl-lvowCAd6DZ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);