// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rzpzhvcawebcvqozqhdy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ6cHpodmNhd2ViY3Zxb3pxaGR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyNzA3NzUsImV4cCI6MjA1Njg0Njc3NX0.AA8eKQs06B-TEi2ZrzZTvtZYpKN-k4M10rXl_wF6rtI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);